<?php
declare(strict_types=1);

namespace labo86\hapi;


class ErrMsg
{
    const SERVICE_NOT_REGISTERED = "SERVICE_NOT_REGISTERED";
    const PARAMETER_IS_NOT_AN_INTEGER = "PARAMETER_IS_NOT_AN_INTEGER";
    const PARAMETER_IS_NOT_A_MULTIPLE_FILE_INPUT = "PARAMETER_IS_NOT_A_MULTIPLE_FILE_INPUT" ;
    const REQUEST_DOES_NOT_HAVE_PARAMETER = "REQUEST_DOES_NOT_HAVE_PARAMETER";
    const PARAMETER_IS_NOT_A_SINGLE_FILE_INPUT = "PARAMETER_IS_NOT_A_SINGLE_FILE_INPUT";
    const PARAMETER_IS_NOT_A_STRING = "PARAMETER_IS_NOT_A_STRING";
    const POST_CONTENT_IS_NOT_A_VALID_JSON = "POST_CONTENT_IS_NOT_A_VALID_JSON";
    const JSON_IN_POST_IS_NOT_AN_ARRAY =  "JSON_IN_POST_IS_NOT_AN_ARRAY";
    const PARAMETER_IS_NOT_AN_ARRAY = "PARAMETER_IS_NOT_AN_ARRAY";
}